#! /bin/tcsh -f
set x=$1
if ("X$1" == "X-lx") then
  set lx="l"
  shift
else
  set lx=""
endif
if ("X$1" == "X-ly") then
  set ly="l"
  shift
else
  set ly=""
endif
set nreg=`climb_and_look_for NREG`
set nnreg=`pipe_run.log | grep -a ^nnreg | head -1`
if (-s $nreg) then
  setenv NREG `cat $nreg`
  echo Set NREG to $NREG "(based on $nreg)"
else
  set NREG=$nnreg[2]
  echo Set NREG to $NREG "(based on log file)"
endif
if (! $?NREG) set NREG=4
if ("X$nnreg" != "X") then
  if ($NREG != $nnreg[2]) then
    echo "NREG in file ($nnreg[2]) does not match $NREG"
    exit
  endif
endif
pipe_run.log | \
  awk 'BEGIN{nrv='$NREG'} \
       /nreg/{nrv=$2;nrx=$3;nry=$4} \
       /pot/{for (i=1;i<=NF-1;i++) pot[i]=$(i+1)*1.602176634e-19;pot[NF]=0} \
       /rsahireg/{rsa=0;for (i=2;i<=NF;i+=nrv+1) rsa+=$i} \
       /rrahireg/{rra=0;for (i=2;i<=NF;i+=nrv+1) rra+=$i} \
       /rqahereg/{rqa=0;for (i=2;i<=NF;i+=nrv+1) rqa+=$i} \
       /rcxhireg/{rcx=0;for (i=2;i<=NF;i+=nrv+1) rcx+=$i} \
       /b2divue/{b2divue=$2} \
       /b2divua/{b2divua=$2} \
       /b2exbe/{b2exbe=$2} \
       /b2exba/{b2exba=$2} \
       /b2visa/{b2visa=$2} \
       /b2joule/{b2joule=$2} \
       /b2fraa/{b2fraa=$2} \
       /b2wrong1/{b2wrong1=$2} \
       /b2wrong2/{b2wrong2=$2} \
       /b2wrong3/{b2wrong3=$2} \
       /b2stbr_she_reg/{b2brhe=$2} \
       /b2stbr_shi_reg/{b2brhi=$2} \
       /fhixreg/&&nrv==1{W=-$3;E=$4} \
       /fhiyreg/&&nrv==1{S=-$3;N=$4} \
       /fhexreg/&&nrv==1{W+=-$3;E+=$4} \
       /fheyreg/&&nrv==1{S+=-$3;N+=$4} \
       /fhixreg/&&nrv==2{W=-$3;E=$4} \
       /fhiyreg/&&nrv==2{S=-$3;N=$5} \
       /fhexreg/&&nrv==2{W+=-$3;E+=$4} \
       /fheyreg/&&nrv==2{S+=-$3;N+=$5} \
       /fhixreg/&&nrv==4{W=-$3;E=$6} \
       /fhiyreg/&&nrv==4{S=-$3-$4-$5;N=$7+$8+$9} \
       /fhexreg/&&nrv==4{W+=-$3;E+=$6} \
       /fheyreg/&&nrv==4{S+=-$3-$4-$5;N+=$7+$8+$9} \
       /fhixreg/&&nrv==8{W=-$3-$7;E=$6+$10} \
       /fhiyreg/&&nrv==8{S=-$3-$4-$5-$10-$11-$12;N=$7+$8+$9+$14+$15+$16} \
       /fhexreg/&&nrv==8{W+=-$3-$7;E+=$6+$10} \
       /fheyreg/&&nrv==8{S+=-$3-$4-$5-$10-$11-$12;N+=$7+$8+$9+$14+$15+$16} \
       /rsanareg/{rsap=0;for (i=2;i<=NF;i+=nrv+1) rsap+=$i*pot[int(i/(nrv+1))+2]} \
       /rranareg/{rrap=0;for (i=2;i<=NF;i+=nrv+1) rrap+=$i*pot[int(i/(nrv+1))+1]} \
       /b2stbr_sna_reg/{b2brnp=0; for (i=2;i<=NF;i+=nrv+1) b2brnp+=$i*pot[int(i/(nrv+1))+2]} \
       BEGIN{print "#cnt rsa rra rqa rcx b2divue b2divua b2exbe b2exba b2visa b2joule b2fraa b2wrong1 b2wrong2 b2wrong3 b2brhe b2brhi rsap rrap b2brnp E N W S E+N+W+S-rsa-rra+rqa-rcx-b2divue-b2divua-b2exbe-b2exba-b2visa-b2joule-b2fraa-b2wrong1-b2wrong2-b2wrong3-b2brhe-b2brhi+rsap-rrap+b2bnrp"} \
       END{print "#cnt rsa rra rqa rcx b2divue b2divua b2exbe b2exba b2visa b2joule b2fraa b2wrong1 b2wrong2 b2wrong3 b2brhe b2brhi rsap rrap b2brnp E N W S E+N+W+S-rsa-rra+rqa-rcx-b2divue-b2divua-b2exbe-b2exba-b2visa-b2joule-b2fraa-b2wrong1-b2wrong2-b2wrong3-b2brhe-b2brhi+rsap-rrap+b2bnrp"} \
       /End tallies by region/{cnt++;print cnt,rsa,rra,rqa,rcx,b2divue,b2divua,b2exbe,b2exba,b2visa,b2joule,b2fraa,b2wrong1,b2wrong2,b2wrong3,b2brhe,b2brhi,rsap,rrap,b2brnp,E,N,W,S,E+N+W+S-rsa-rra+rqa-rcx-b2divue-b2divua-b2exbe-b2exba-b2visa-b2joule-b2fraa-b2wrong1-b2wrong2-b2wrong3-b2brhe-b2brhi+rsap-rrap+b2bnrp}' | \
  plot ${lx}x${ly}yplot24 rsa rra rqa rcx b2divue b2divua b2exbe b2exba b2visa b2joule b2fraa b2wrong1 b2wrong2 b2wrong3 b2brhe b2brhi rsap rrap b2brnp E N W S E+N+W+S-rsa-rra+rqa-rcx-b2divue-b2divua-b2exbe-b2exba-b2visa-b2joule-b2fraa-b2wrong1-b2wrong2-b2wrong3-b2brhe-b2brhi+rsap-rrap+b2bnrp iteration 'Power (W)' "`basename $0` `chop_pwd 40`"
