#! /bin/csh -f
set nreg=`climb_and_look_for NREG`
set nnreg=`pipe_run.log | grep ^nnreg | head -1`
if (-s $nreg) then
  setenv NREG `cat $nreg`
  echo Set NREG to $NREG "(based on $nreg)"
else
  set NREG=$nnreg[2]
  echo Set NREG to $NREG "(based on log file)"
endif
set ns=`get_solps_fluids | wc -w`
echo Set number of species to $ns
if (! $?NREG) set NREG = 4
if ("X$nnreg" != "X") then
  if ($NREG != $nnreg[2]) then
    echo "NREG in file ($nnreg[2]) does not match $NREG"
    exit
  endif
endif
switch ($NREG)
  case "4":
    pipe_run.log | \
      egrep -a 'fna.reg|b2stbr_sna_reg|nnreg|Total profile-source na|tallies' | \
      awk 'BEGIN{ext=0} \
           /nnreg/{nvreg=$2;nxreg=$3;nyreg=$4} \
           /Total profile-source na: *0 /{ext=$5} \
           /Total profile-source na: *1 /{ext+=$5} \
           /fnaxreg/{dev=0;for (i=0;i<'$ns';i++) dev+=-$(3+(nxreg+1)*i)+$(6+(nxreg+1)*i)}\
		   /fnayreg/{for (i=0;i<'$ns';i++) dev+=-$(3+(nyreg+1)*i)-$(4+(nyreg+1)*i)-$(5+(nyreg+1)*i)+$(7+(nyreg+1)*i)+$(8+(nyreg+1)*i)+$(9+(nyreg+1)*i)}\
		   /b2stbr_sna_reg/{recyc=0;for (i=0;i<'$ns';i++) recyc+=$(2+(nvreg+1)*i)}\
		   /End tallies by region/{cnt++;print cnt,dev,ext,recyc,dev-ext-recyc;dev=0}' | \
      plot x$1yplot4 N-S+E-W EXT RECYC ERR "`basename $0` `chop_pwd 40`"
    breaksw
  case "8":
    pipe_run.log | \
      egrep -a 'fna.reg|b2stbr_sna_reg|nnreg|Total profile-source na|tallies' | \
      awk 'BEGIN{ext=0} \
           /nnreg/{nvreg=$2;nxreg=$3;nyreg=$4} \
           /Total profile-source na: *0 /{ext=$5} \
           /Total profile-source na: *1 /{ext+=$5} \
           /fnaxreg/{dev=0;for (i=0;i<'$ns';i++) dev+=-$(3+(nxreg+1)*i)+$(6+(nxreg+1)*i)-$(7+(nxreg+1)*i)+$(10+(nxreg+1)*i)}\
		   /fnayreg/{for (i=0;i<'$ns';i++) dev+=-$(3+(nyreg+1)*i)-$(4+(nyreg+1)*i)-$(5+(nyreg+1)*i)+$(7+(nyreg+1)*i)+$(8+(nyreg+1)*i)+$(9+(nyreg+1)*i)-$(10+
		   (nyreg+1)*i)-$(11+(nyreg+1)*i)-$(12+(nyreg+1)*i)+$(14+(nyreg+1)*i)+$(15+(nyreg+1)*i)+$(16+(nyreg+1)*i)}\
		   /b2stbr_sna_reg/{recyc=0;for (i=0;i<'$ns';i++) recyc+=$(2+(nvreg+1)*i)}\
           /End tallies by region/{cnt++;print cnt,dev,ext,recyc,dev-ext-recyc;dev=0}' | \
      plot x$1yplot4 N-S+E-W EXT RECYC ERR
    breaksw
  default:
    echo "Unusual number of regions: Not sure what to do!"
    echo "NREG = " $NREG
endsw
